name: Build, Teste e An치lise Sonar

on:
  push:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      #primeiro baixa o c칩digo
      - name: 1. Checkout do c칩digo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      #java
      - name: 2. Configurar Java (JDK 20)
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'

      #construir testar e analisar com o sonar
      - name: 3. Build, Teste e An치lise Sonar (Maven)
        run: mvn -B verify package sonar:sonar
             -Dsonar.organization=henriqrocha 
             -Dsonar.projectKey=HenriqRocha_ES2
             -Dsonar.host.url=https://sonarcloud.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}